services:
  - type: web
    name: backend-gastofacil
    runtime: node
    env: node
    buildCommand: npm install && npx nest build
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
